name: setup
description: 'basic setup project with npm ci'

runs:
  using: "composite"
  steps:
    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        check-latest: false
        cache: npm
        registry-url: 'https://registry.npmjs.org'
    - name: install dependencies
      run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline  --no-fund
      # only run npm ci when restoring the cache didn’t work to save some time
      # as npm ci would remove the node_modules again
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
    - run: npm ls --depth 0 || true
      shell: bash
