contact_links:
  - name: 🤔 Support Question
    url: https://github.com/Ephigenia/ikea-availability-checker/discussions
    about: This issue tracker is not for support questions. Please post your question in the discussions
