name: npm-new-packages

on:
  pull_request:
    paths:
      # run only when one of the files matching the glob patterns changed
      - 'package.json'
      - 'package-lock.json'

jobs:
  check_new_dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # required by hiwelo/new-dependencies-action
      pull-requests: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Check for new dependencies
        uses: hiwelo/new-dependencies-action@1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
