name: release

on:
  # run only when default workflow was successful
  workflow_run:
    workflows: ["default"]
    # run when there are new commits for specific branches
    branches:
    - master
    - next
    - next-major
    - alpha
    - beta
    types:
    - completed

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    # automatic github and npm package release creation using semantic-release
    # .releaserc.json defines which branches and/or tags are released
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run semantic-release
