name: smokey

on:
  push:
  schedule:
    - cron: "0 0/12 * * *"

jobs:
  smokey:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup
    - run: scripts/smokey.sh
    - run: scripts/smokey-formats.sh
